# Generated by Django 3.2.8 on 2022-10-29 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request_music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('lat', models.CharField(max_length=15)),
                ('log', models.CharField(max_length=15)),
                ('block', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gender_Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.barconfig')),
                ('gender_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_1', to='request_music.gender')),
                ('gender_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_10', to='request_music.gender')),
                ('gender_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_2', to='request_music.gender')),
                ('gender_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_3', to='request_music.gender')),
                ('gender_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_4', to='request_music.gender')),
                ('gender_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_5', to='request_music.gender')),
                ('gender_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_6', to='request_music.gender')),
                ('gender_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_7', to='request_music.gender')),
                ('gender_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_8', to='request_music.gender')),
                ('gender_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_9', to='request_music.gender')),
            ],
        ),
    ]
