# Generated by Django 3.2.8 on 2022-10-29 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_barconfig_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='W0ZDZk0OAV', max_length=10)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('lat', models.CharField(max_length=15)),
                ('log', models.CharField(max_length=15)),
                ('block', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='gender_bar',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.barconfigs'),
        ),
        migrations.DeleteModel(
            name='BarConfig',
        ),
    ]
