# Generated by Django 3.2.8 on 2022-10-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0004_auto_20221029_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barconfigs',
            name='code',
            field=models.CharField(default='hscYNvYBqF', max_length=10),
        ),
    ]
